import pathlib

projectPath = pathlib.Path(__file__).parent.absolute()
configPath = projectPath.joinpath("config").absolute()
fnjvAnuraPath = configPath.joinpath("FNJV_Anura.yaml").absolute()
outputPath = projectPath.joinpath("output").absolute()
speciesFile = outputPath.joinpath("species.csv").absolute()
familiesFile = outputPath.joinpath("families.csv").absolute()
gendersFile = outputPath.joinpath("genders.csv").absolute()
recordingsFile = outputPath.joinpath("recordings.csv").absolute()
audioDataFile = outputPath.joinpath("audioData.npz").absolute()
checkpointPath = projectPath.joinpath("checkpoint").absolute()
speciesModelPath = checkpointPath.joinpath("speciesRNN").absolute()
speciesModelWeightsFile = speciesModelPath.joinpath("vocatoadCheckpoint").absolute()
familyModelPath = checkpointPath.joinpath("familyRNN").absolute()
familyModelWeightsFile = familyModelPath.joinpath("vocatoadCheckpoint").absolute()
familyCNNModelPath = checkpointPath.joinpath("familyCNN").absolute()
familyCNNModelWeightsFile = familyCNNModelPath.joinpath("vocatoadCheckpoint").absolute()
genderCNNModelPath = checkpointPath.joinpath("genderCNN").absolute()
genderCNNModelWeightsFile = genderCNNModelPath.joinpath("vocatoadCheckpoint").absolute()
speciesCNNModelPath = checkpointPath.joinpath("speciesCNN").absolute()
speciesCNNModelWeightsFile = speciesCNNModelPath.joinpath("vocatoadCheckpoint").absolute()
savedModelsPath = projectPath.joinpath("savedmodels").absolute()
reportsPath = projectPath.joinpath("reports").absolute()
speciesReport = reportsPath.joinpath("speciesReport.csv").absolute()
familiesReport = reportsPath.joinpath("familiesReport.csv").absolute()
gendersReport = reportsPath.joinpath("gendersReport.csv").absolute()


outputPath.mkdir(exist_ok=True)
checkpointPath.mkdir(exist_ok=True)
speciesModelPath.mkdir(exist_ok=True)
familyModelPath.mkdir(exist_ok=True)
familyCNNModelPath.mkdir(exist_ok=True)
genderCNNModelPath.mkdir(exist_ok=True)
speciesCNNModelPath.mkdir(exist_ok=True)
savedModelsPath.mkdir(exist_ok=True)
reportsPath.mkdir(exist_ok=True)